---
apiVersion: v1
kind: Namespace
metadata:
  name: iit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: iit
  name: satellite
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: satelliteapp
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: satelliteapp
    spec:
      containers:
      - image: 0710136772/satelliteapp-img:main
        imagePullPolicy: Always
        name: satelliteapp
        ports:
        - containerPort: 8089
---
apiVersion: v1
kind: Service
metadata:
  namespace: iit
  name: satellite-service
spec:
  type: NodePort
  ports:
    - port: 8089
      targetPort: 8089
      protocol: TCP
  selector:
    app.kubernetes.io/name: satelliteapp
  type: LoadBalancer
status:
  loadBalancer: {}  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: iit
  name: orbit
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: orbitapp
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: orbitapp
    spec:
      containers:
      - image: 0710136772/orbitapp-img:main
        imagePullPolicy: Always
        name: orbitapp
        ports:
        - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  namespace: iit
  name: orbit-service
spec:
  type: NodePort
  ports:
    - port: 8088
      targetPort: 8088
      protocol: TCP
  selector:
    app.kubernetes.io/name: orbitapp
  type: LoadBalancer
status:
  loadBalancer: {}